version: 2.1

executors:
  docker_git:
    docker:
      - image: docker:stable-git
  node-executor:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.14-browsers
  ecs-deploy:
    resource_class: small
    docker:
      - image: pbxx/go-ecs-deploy:master-latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD

commands:
  deploy:
    parameters:
      type:
        type: enum
        enum: ['service', 'oneshot']
        default: 'service'
      cluster:
        type: enum
        enum: ['dev', 'stg', 'prod']
      role_arn:
        type: string
      config_repo:
        type: string
      config_dir:
        type: string
      task_file:
        type: string
        default: 'task.json'
    steps:
      - run: |
          git clone git@github.com:promoboxx/<< parameters.config_repo >>.git
          export AWS_REGION="us-east-1"
          export AWS_DEFAULT_REGION="us-east-1"

          jq --arg image "pbxx/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" '.containerDefinitions[0].image = $image' ./<< parameters.config_repo >>/<< parameters.config_dir >>/<< parameters.task_file >> > temp_task.json
          jq --arg token "$(date +%s)" '.clientToken = $token' ./<< parameters.config_repo >>/<< parameters.config_dir >>/service.json > temp_service.json

          echo "------------------------------------------------------------------------------------------"
          jq '.' temp_task.json
          echo "------------------------------------------------------------------------------------------"
          jq '.' temp_service.json
          echo "------------------------------------------------------------------------------------------"

          /go-ecs-deploy -task temp_task.json -service temp_service.json -type << parameters.type >> -cluster << parameters.cluster >> -roleArn << parameters.role_arn >> -roleSessionName circleci-<< parameters.cluster >>-deploy -roleExternalID ecs-<< parameters.cluster >>-deploy -count 120

  graph_push:
    parameters:
      endpoint:
        type: string
    steps:
      - run: |
          npx apollo service:push --endpoint=<< parameters.endpoint >>

  graph_check:
    parameters:
      endpoint:
        type: string
    steps:
      - run: |
          npx apollo service:check --endpoint=<< parameters.endpoint >>

jobs:
  prepare:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Setup NPM registry authentication
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --no-progress
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
            - ~/.ssh
  docker_build_and_push:
    executor: docker_git
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"

          docker build -t pbxx/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
          docker tag pbxx/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} pbxx/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest

          docker push pbxx/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
          docker push pbxx/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest
  deploy_dev:
    executor: ecs-deploy
    steps:
      - attach_workspace:
          at: .
      - deploy:
          cluster: dev
          role_arn: ${DEV_ECS_DEPLOY_ROLE_ARN}
          config_repo: deploy-config-dev
          config_dir: graphql-server
  graph_check_dev:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - graph_push:
          endpoint: https://graph.dev.pbxx.io
  deploy_stg:
    executor: ecs-deploy
    steps:
      - attach_workspace:
          at: .
      - deploy:
          cluster: stg
          role_arn: ${STG_ECS_DEPLOY_ROLE_ARN}
          config_repo: deploy-config-stg
          config_dir: graphql-server
  graph_check_stg:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - graph_push:
          endpoint: https://graph.stg.pbxx.io
  deploy_prod:
    executor: ecs-deploy
    steps:
      - attach_workspace:
          at: .
      - deploy:
          cluster: prod
          role_arn: ${PROD_ECS_DEPLOY_ROLE_ARN}
          config_repo: deploy-config-prod
          config_dir: graphql-server
  graph_check_prod:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - graph_push:
          endpoint: https://graph.promoboxx.com

workflows:
  version: 2

  deploy:
    jobs:
      - prepare:
          context: spa
          filters:
            branches:
              only: terraform-setup
              # only: master
      - docker_build_and_push:
          context: 'dockerhub'
          requires:
            - prepare
      - deploy_dev:
          context: 'dockerhub'
          requires:
            - docker_build_and_push
      - graph_check_dev:
          requires:
            - deploy_dev
      - approve_deploy_stg:
          type: approval
          requires:
            - deploy_dev
      - deploy_stg:
          context: 'dockerhub'
          requires:
            - approve_deploy_stg
      - graph_check_stg:
          requires:
            - deploy_stg
      - approve_deploy_prod:
          type: approval
          requires:
            - deploy_stg
      - deploy_prod:
          context: 'dockerhub'
          requires:
            - approve_deploy_prod
      - graph_check_prod:
          requires:
            - deploy_prod
